name: Create QA Ephemeral

on:
  push:
    branches:
      - main  
  pull_request:
    branches: [ main, master ]

jobs:
  qa_ephemeral:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Add Ephemeral Link Title
        id: ephemeral_text
        uses: actions/github-script@v6
        with:
          result-encoding: string 
          script: |
            const original_body = context
            console.dir(original_body,{depth:null});
