name: Manual trigger

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'  # Default value if not specified

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      # Add your deployment steps here
      - name: Print PR Number, Commit ID, and Ref Name
        run: |
          echo "PR Number: ${{ github.event.number }}"
          echo "Commit ID: ${{ github.sha }}"
          echo "Ref Name: ${{ github.ref }}"
