name: Simple Dispatch Workflow

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Print PR Number, Commit ID, and Ref Name
        run: |
          echo "PR Number: ${{ github.event.pull_request.number }}"
          echo "Commit ID: ${{ github.sha }}"
          echo "Ref Name: ${{ github.ref }}"
