name: Manual trigger

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'  # Default value if not specified

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      # Add your deployment steps here
      - name: Deploy to ${{ github.event.inputs.environment }}
        run: |
          echo Deploying to ${{ github.event.inputs.environment }}
